project_id = "sujyalrzbubvhpkntwja"

[functions.google-calendar]
verify_jwt = false

[functions.news-proxy]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-broadcast]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
