#!/bin/bash

# Build all call lists in standard format
# Usage: ./build-call-lists.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LISTS_DIR="$SCRIPT_DIR/../call-lists"

mkdir -p "$LISTS_DIR"

echo "📋 Building call lists..."

# 1. Nurture sequences (already done in nurture-call-list.html)
# cp $SCRIPT_DIR/../nurture-call-list.html $LISTS_DIR/nurture-sequences.html
# echo "✓ Nurture sequences call list"

# 2. Generate template file
cat > $SCRIPT_DIR/../call-lists/README.md << 'DOC'
# Call Lists

All call lists use the standard format generated by `scripts/generate-call-list.js`.

## Structure

Each list has:
- **Header** with title and metadata
- **Sections** (🔴 HOT, 🟡 WARM, 🔵 COOL)
- **Cards** with contact info, wants, notes, and action buttons

## Creating a New List

1. Create a JSON file following `scripts/call-list-template.json`
2. Run: `node scripts/generate-call-list.js data.json output.html`
3. Open `output.html` in browser or deploy to Netlify

## JSON Format

```json
{
  "title": "📞 Your Title",
  "subtitle": "Description · Generated DATE",
  "filename": "output.html",
  "sections": [
    {
      "title": "HOT — Urgent (3 contacts)",
      "emoji": "🔴",
      "type": "hot",
      "contacts": [
        {
          "number": 1,
          "name": "Name",
          "role": "Type/status",
          "phone": "0412 345 678",
          "email": "email@example.com",
          "overdue": "5 days overdue",
          "location": "City, QLD",
          "wants": "What next",
          "note": "Context & details"
        }
      ]
    }
  ],
  "footer": "Location · List Type · CRM-verified DATE"
}
```

## Examples

- `nurture-sequences.json` → nurture-sequences.html
- `buyer-call-lists/` → property-specific buyer lists
- `property-briefs.json` → contact lists per property

## Deploying to Netlify

```bash
# Push call-lists/ folder to repo
git add call-lists/
git commit -m "Update call lists"
git push

# Or manually deploy via Netlify drag-and-drop
```

DOC

echo "✓ Created call-lists directory and README"

# Show summary
echo ""
echo "📂 Call lists directory structure:"
ls -la $LISTS_DIR 2>/dev/null || echo "   (empty, ready for new lists)"

echo ""
echo "✅ To create a new call list:"
echo "   1. Create JSON file: $LISTS_DIR/my-list.json"
echo "   2. Generate HTML: node scripts/generate-call-list.js call-lists/my-list.json"
echo "   3. Open output.html or deploy to Netlify"
