// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Expected Supabase project ref (single source: supabase/project-ref). Must match VITE_SUPABASE_URL. */
const EXPECTED_PROJECT_REF = "sujyalrzbubvhpkntwja";

const IS_TEST = Boolean(import.meta.env?.VITEST) || import.meta.env?.MODE === "test";
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? (IS_TEST ? "https://example.supabase.co" : undefined);
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? (IS_TEST ? "test-anon-key" : undefined);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Copy .env.example to .env and set them."
  );
}

if (import.meta.env.DEV && !SUPABASE_URL.includes(EXPECTED_PROJECT_REF)) {
  console.warn(
    `[Supabase] VITE_SUPABASE_URL points to a different project than expected. ` +
      `Expected: https://${EXPECTED_PROJECT_REF}.supabase.co. ` +
      `Update .env and restart the dev server to fix 400 errors and missing columns.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});